version: "3"

services:
  cms:
    image: node:14.3.0
    ports:
      - 1337:1337
    volumes:
      - ./cms:/usr/local/app
    depends_on:
      - db
    restart: always
    working_dir: /usr/local/app
    entrypoint: "/bin/bash"
    command: "-c \"if [ ! -d \"node_modules\" ]; then npm i; fi; npm run develop\""
    environment:
      - DATABASE_HOST=db
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
        POSTGRES_DB: bpm
        POSTGRES_PASSWORD: root123
        POSTGRES_USER: postgres
  frontend:
    image: node:14.3.0
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/usr/local/app
    restart: always
    working_dir: /usr/local/app
    entrypoint: "/bin/bash"
    command: "-c \"if [ ! -d \"node_modules\" ]; then npm i; fi; npm run dev\""
